name: 🎭 Tests
on:
  push:
    paths-ignore:
      - .chglog/**
      - .github/**
      - '!.github/workflows/tests.yml'
      - .editorconfig
      - .gitattributes
      - .gitignore
      - .htaccess
      - '**.md'
    branches:
      - 'master'
  pull_request:
    paths-ignore:
      - .chglog/**
      - .github/**
      - '!.github/workflows/tests.yml'
      - .editorconfig
      - .gitattributes
      - .gitignore
      - .htaccess
      - '**.md'
    branches:
      - 'master'

jobs:
  silverstripe-module-6:
    name: 🧰 Silverstripe Module Testsuite 6
    uses: syntro-opensource/workflows/.github/workflows/silverstripe-module-6.yml@master
    with:
      phpunit: true
      phpstan: true
  silverstripe-module-codecoverage:
    name: 📊 Silverstripe Code Coverage
    uses: syntro-opensource/workflows/.github/workflows/silverstripe-module-codecoverage.yml@master
    with:
      php_version: 8.3
      silverstripe_version: 6.0
  silverstripe-phpcs:
    name: 🧹 Silverstripe PHPCS
    uses: syntro-opensource/workflows/.github/workflows/silverstripe-phpcs.yml@master
    with:
      dir: src/
